blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog_list'),
    path('new/', views.BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/update/', views.BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete/', views.BlogDeleteView.as_view(), name='blog_delete'),
    path("tag/<str:tag>/", views.BlogTagListView.as_view(), name="blog_tag"),
    path("category/<str:category>/", views.BlogCategoryListView.as_view(), name="blog_cateogry"),
    path('author/<str:username>/', views.AuthorPostsListView.as_view(), name='blog_author'),
    # comment 추가 url 추가
    path(
        "<int:pk>/comment_create/",
        views.CommentCreateView.as_view(),
        name="comment_create",
    ),    
    # comment 삭제 url 추가
    path(
        "<int:pk>/comment_delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    # path('', RedirectView.as_view(url='tube/'), name='root'),
    path('', RedirectView.as_view(pattern_name='blog:blog_list'), name='root'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import uuid
import os
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField 
from django.utils.html import strip_tags


class Blog(models.Model):
    title = models.CharField(max_length=100)

    thumb_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    content = HTMLField() # models.TextField()에서 수정   
    
    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, help_text="블로그 글의 카테고리를 선택하세요.")
    view_count = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'


class Comment(models.Model):
    post = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='comments'
    )
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    # 댓글 삭제시 DB에서 완전히 지우지 않고, 안 보이도록 설정하기 위함.
    is_deleted = models.BooleanField(default=False)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        if self.is_deleted:
            return "삭제되었습니다."
        else:
            # HTML 등을 제거
            return strip_tags(self.message)
    
    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name
    

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, help_text="블로그 글을 분류를 입력하세요. ex)소설")

    def __str__(self):
        return self.name
    

blog/forms.py
from django import forms
from .models import Blog, Comment, Tag, Category
from tinymce.widgets import TinyMCE

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    tags = forms.CharField(required=False, help_text="태그를 입력 해주세요. 예)소설, 작가, 재밌다")  # tags 필드 추가
    
    class Meta:
        model = Blog
        fields = ['title', 'thumb_image', 'content', 'category'] # 'tags' 필드는 별도 처리
        widgets = {         
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['thumb_image'].required = True  # 썸네일 이미지 필드를 필수 항목으로 설정
        self.fields['category'].required = True  # 썸네일 이미지 필드를 필수 항목으로 설정

    def clean_thumb_image(self):
        thumb_image = self.cleaned_data.get('thumb_image')
        if thumb_image:
            return thumb_image
        else:
            raise forms.ValidationError("썸네일 이미지는 필수 입력 항목입니다.")

    def clean_content(self):
        content = self.cleaned_data.get('content')
        if not content:
            raise forms.ValidationError('본문 내용을 입력해주세요.')
        return content

    def clean_tags(self):
        tags_str = self.cleaned_data.get('tags', '')
        if not tags_str:
            return []
        tags_list = [tag.strip() for tag in tags_str.split(',')]
        return tags_list


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView
from .models import Blog, Comment, Tag, Category
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


class BlogListView(ListView):
    model = Blog
    context_object_name = 'posts'  # 컨텍스트 변수 이름 설정
    paginate_by = 8  # 한 페이지에 보여줄 객체 수
    template_name = "blog/blog_list.html"

    def get_queryset(self):
        qs = super().get_queryset().order_by('-created_at')
        q = self.request.GET.get('q', '')   # 제목 검색 쿼리
        if q:
            qs = qs.filter(title__icontains=q)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['categories'] = Category.objects.all()  # 카테고리 목록 전달
        return context    
blog_list = BlogListView.as_view()


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = PostForm
    success_url = reverse_lazy('blog:blog_list')
    template_name = 'blog/form.html'

    def form_valid(self, form):
        blog = form.save(commit=False) # commit=False는 DB에 저장하지 않고 객체만 반환
        blog.author = self.request.user
        blog.save()

        # 태그 처리
        tags_list = form.cleaned_data.get('tags', [])
        for tag_name in tags_list:
            tag, created = Tag.objects.get_or_create(name=tag_name)
            blog.tags.add(tag)
        return super().form_valid(form)
blog_create = BlogCreateView.as_view()


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog
    context_object_name = 'post'
    # context_object_name = 'licat_objects' # {{licat_objects.title}} 이런식으로 사용 가능

    def get_context_data(self, **kwargs):
        '''
        여기서 원하는 쿼리셋이나 object를 추가한 후 템플릿으로 전달할 수 있습니다.
        '''
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()

        # 현재 포스트 객체 가져와서
        post = context['post']  
        # 삭제되지 않은 댓글만 골라서 보여줌.
        #comments = post.comments.filter(is_deleted=False)  
        # 모든 댓글 보여주도록 수정. 
        comments = Comment.objects.filter(post=post, parent__isnull=True)  # 실제 DB에 삭제하지 않고, 삭제되었습니다. 라고 뜨게 함
        context['comments'] = comments  # 필터링된 댓글을 컨텍스트에 추가
         
        context['top_tags'] = Tag.objects.annotate(num_posts=Count('blog')).order_by('-num_posts')[:5] # 가장 많이 사용된 태그 5개 추가
        context['categories'] = Category.objects.all()  # 카테고리 목록 추가   
        context['recent_posts'] = Blog.objects.order_by('-created_at')[:3]  # 최근 블로그 글 3개 추가     
        return context
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        print(self.kwargs)
        post = get_object_or_404(Blog, pk=pk)
        post.view_count += 1
        post.save()
        return super().get_object(queryset)
blog_detail = BlogDetailView.as_view()


class BlogUpdateView(UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = PostForm
    success_url = reverse_lazy('blog:blog_list')
    template_name = 'blog/form.html'

    def test_func(self): # UserPassesTestMixin에 있고 test_func() 메서드를 오버라이딩, True, False 값으로 접근 제한
        return self.get_object().author == self.request.user
blog_update = BlogUpdateView.as_view()


class BlogDeleteView(UserPassesTestMixin, DeleteView):
    model = Blog
    template_name = 'blog/blog_delete.html'
    success_url = reverse_lazy('blog:blog_list')

    def test_func(self): # UserPassesTestMixin에 있고 test_func() 메서드를 오버라이딩, True, False 값으로 접근 제한
        return self.get_object().author == self.request.user
blog_delete = BlogDeleteView.as_view()


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('blog:blog_detail', kwargs={'pk': self.object.post.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user  # 댓글 작성자 설정
        form.instance.post = get_object_or_404(Blog, pk=self.kwargs['pk'])  # 댓글이 달릴 글 설정
        return super().form_valid(form)
    

class CommentDeleteView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = []  # 뷰에서 업데이트할 필드가 없으므로 비워둡니다.
    template_name = 'blog/comment_delete.html'

    def form_valid(self, form):
        """
        폼 유효성 검사가 성공하면 호출됩니다.
        댓글의 is_deleted를 True로 설정합니다.
        """
        comment = form.save(commit=False)
        comment.is_deleted = True
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return reverse_lazy('blog:blog_detail', kwargs={'pk': comment.post.pk})
    
    def get_queryset(self):
        """ 사용자가 자신의 댓글만 삭제할 수 있도록 합니다. """
        qs = super().get_queryset()
        return qs.filter(author=self.request.user)


class BlogTagListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        tag_name = self.kwargs['tag']
        return Blog.objects.filter(tags__name=tag_name).order_by('-created_at')


class BlogCategoryListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        category_name = self.kwargs['category']
        return Blog.objects.filter(category__name=category_name).order_by('-created_at')
    

class AuthorPostsListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Blog.objects.filter(author__username=self.kwargs.get('username')).order_by('-created_at')

templates/blog/_comment.html
{% load static %}
<li class="comment">
    <div class="vcard bio">
      {% with profile=comment.author.profile %}
        {% if profile %}
          {% if profile.photo %}
            <img src="{{ profile.photo.url }}" alt="Image placeholder" class="img-fluid block-5">
          {% else %}
            <img src="{% static 'images/default_profile.png' %}" alt="Default Image" class="img-fluid  block-5">
          {% endif %}
        {% else %}
          <img src="{% static 'images/default_profile.png' %}" alt="Default Image" class="img-fluid  block-5">
        {% endif %}
      {% endwith %}
    </div>
    <div class="comment-body">
      <h6>{{ comment.author }} <small class="text-muted">{{ comment.created_at|date:"Y-m-d H:i" }}</small></h6>
      {% if comment.is_deleted %}
        <p>댓글이 삭제되었습니다.</p>
      {% else %}
        <p>{{ comment.message }}</p>
        <p>
          <a href="#commentForm" class="reply" onclick="setParentId({{ comment.pk }})">Reply</a>
          {% if request.user == comment.author %}
            <a href="{% url 'blog:comment_delete' comment.pk %}" class="reply">댓글삭제</a>
          {% endif %}
        </p>
      {% endif %}
    </div>
    {% with replies=comment.replies.all %}
    {% if replies %}
      <ul class="children">
        {% for reply in replies %}
          {% include '_comment.html' with comment=reply %}
        {% endfor %}
      </ul>
    {% endif %}
    {% endwith %}
</li>

templates/blog/blog_delete.html
<h1>글 삭제</h1>

<form method="post">
    {% csrf_token %}
    <p>정말로 "{{ object.title }}" 글을 삭제하시겠습니까?</p>
    <input type="submit" value="삭제" class="btn btn-danger">
    <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-secondary">취소</a>
</form>

templates/blog/blog_detail.html
{% extends 'base.html' %}
{% block contents %}
{% load static %}
    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 ftco-animate order-md-last">
            <h2 class="mb-3">{{post.title}}</h2>
            <p>{{post.content|safe}}</p>
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:blog_tag' tag.name %}" class="tag-cloud-link">{{ tag.name }}</a>
                {% endfor %}
              </div>
            </div>            
            <div class="about-author d-flex p-4 bg-light">
              <div class="bio align-self-md-center mr-4">
                {% if post.author.profile.photo %}
                  <img src="{{ post.author.profile.photo.url }}" alt="Image placeholder" class="img-fluid mb-4 block-10">
                {% else %}
                  <img src="{% static 'images/default_profile.png' %}" alt="Default Image" class="img-fluid mb-4 block-10">
                {% endif %}
              </div>
              <div class="desc align-self-md-center">
                <h3>{{post.author}}</h3>
                <p>{{post.author.profile.message}}</p>
              </div>
            </div>
            <!-- 로그인을 했고, 내가 이 글에 글쓴이라고 한다면 삭제와 업데이트 버튼 노출 -->
            {% if user.is_authenticated and user == post.author %}
            <div class="d-flex">
                <a class="btn btn-primary" href="{% url 'blog:blog_update' post.pk %}">수정</a>
                <a class="btn btn-danger ml-2" href="{% url 'blog:blog_delete' post.pk %}">삭제</a>
            </div>
            {% endif %}
            {% if comments.count > 0 %}
            <div class="pt-5 mt-5">
              <h4 class="mb-5">전체 댓글: {{comments.count}}</h4>
              <ul class="comment-list">
                {% for comment in comments %}
                  {% if comment.parent is None %}
                    {% include 'blog/_comment.html' %}
                  {% endif %}
                {% endfor %}
              </ul>                       
            </div>
            {% else %}
              <p><br>아직 댓글이 없습니다.</p>
            {% endif %}
            <div class="about-author p-4 bg-light">
              <div class="comment-form">
                <form action="{% url 'blog:comment_create' post.pk %}" method="post" id="commentForm">
                  {% csrf_token %}
                  <input type="hidden" name="parent_id" id="parent_id" value="">
                  <div class="form-group">
                    <label for="{{ comment_form.message.id_for_label }}" class="sr-only">내용</label>
                    <textarea class="form-control" name="{{ comment_form.message.name }}" id="{{ comment_form.message.id_for_label }}" rows="3" placeholder="댓글을 입력하세요" required></textarea>
                  </div>
                  <button type="submit" class="btn btn-primary">댓글 작성</button>
                </form>
              </div>
            </div>
          </div> <!-- .col-md-8 -->
          <div class="col-lg-3 sidebar ftco-animate">
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                {% for category in categories %}
                  <li>
                    <a href="{% url 'blog:blog_cateogry' category.name %}">
                      {{ category.name }} <span>({{ category.blog_set.count }})</span>
                    </a>
                  </li>
                {% endfor %}
              </div>
            </div>
            <div class="sidebar-box">
              <form action="{% url 'blog:blog_list' %}" method="GET">
                <div class="form-group">
                  <h3>search</h3>
                  <input type="text" name="q" value="{{ request.GET.q }}">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <h3>Recent Blog</h3>
              {% for post in recent_posts %}
                <div class="block-21 mb-4 d-flex">
                  <a class="blog-img mr-4" style="background-image: url({{ post.thumb_image.url }});"></a>
                  <div class="text">
                    <h3 class="heading"><a href="{% url 'blog:blog_detail' post.pk %}">{{ post.title }}</a></h3>
                    <div class="meta">
                      <div><span class="icon-calendar"></span> {{ post.created_at|date:"Y-m-d" }}</div>
                      <div><span class="icon-person"></span> {{ post.author }}</div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Tag Cloud</h3>
              <div class="tagcloud">
                {% for tag in top_tags %}
                <a href="{% url 'blog:blog_tag' tag.name %}" class="tag-cloud-link">{{tag.name}}</a>
                {% endfor %}
              </div>
            </div>
        </div>
      </div>
    </section> <!-- .section -->
    {% endblock %}

templates/blog/blog_list.html
{% extends 'base.html' %}
{% block contents %}
{% load static %}
  <section class="ftco-section">
      <div class="container">
        <div class="row d-flex">
          {% for post in posts %}
          <div class="col-md-3 ftco-animate">
            <div class="blog-entry align-self-stretch">
              <a href="{% url 'blog:blog_detail' post.pk %}" class="block-20" style="background-image: url({{post.thumb_image.url}});">
              </a>

              <div class="text mt-3 d-block">
                <h3 class="heading mt-3"><a href="{% url 'blog:blog_detail' post.pk %}">{{ post.title|truncatechars:14 }}</a></h3>
                <div class="meta mb-3">
                  <div>
                    <a href="#"><span class="mr-3">{{ post.created_at|date:"Y-m-d H:i" }}</span> 조회수: {{ post.view_count }}</a><br>
                    <a href="{% url 'blog:blog_author' post.author.username %}">{{ post.author }}</a>
                    <a href="{% url 'blog:blog_detail' post.pk %}" class="meta-chat"><span class="icon-chat"></span>{{ post.comments.count }}</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <form action="" method="GET">
                <input type="text" name="q" value="{{ request.GET.q }}">
                <input type="submit" value="검색">
              </form>
              <a href="{% url 'blog:blog_create' %}">업로드</a>
            </div>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                {% if page_obj.has_previous %}
                  <li><a href="?page=1">&laquo;</a></li>
                  <li><a href="?page={{ posts.previous_page_number }}">&lt;</a></li>
                {% endif %}
                
                {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                    <li class="active"><span>{{ num }}</span></li>
                  {% else %}
                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                  {% endif %}
                {% endfor %}
                
                {% if page_obj.has_next %}
                  <li><a href="?page={{ posts.next_page_number }}">&gt;</a></li>
                  <li><a href="?page={{ posts.paginator.num_pages }}">&raquo;</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>    
      </div>
    </section>
    {% endblock %}

templates/blog/comment_delete.html
<h1>댓글 삭제</h1>

<form method="post">
    {% csrf_token %}
    <p>댓글을 삭제하시겠습니까?</p>
    <input type="submit" value="네!" class="btn btn-primary">
</form>

templates/blog/form.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
<form action="{% if form.instance.pk %}
                {% url 'blog:blog_update' form.instance.pk %}
              {% else %}
                {% url 'blog:blog_create' %}
              {% endif %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="ftco-section">
        <div class="container">
            <!-- Title Field -->
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="title" name="{{ form.title.name }}" value="{{ form.title.value|default_if_none:'' }}" required>
                {% if form.title.errors %}
                <div class="invalid-feedback">
                    {{ form.title.errors }}
                </div>
                {% endif %}
            </div>

            <!-- Thumb Image Field -->
            <div class="mb-3">
                <label for="thumb_image" class="form-label">Thumb Image</label>
                {{ form.thumb_image }}
                {% if form.thumb_image.errors %}
                <div class="invalid-feedback">
                    {{ form.thumb_image.errors }}
                </div>
                {% endif %}
            </div>

            <!-- Content Field (assuming you want to use TinyMCE for this field) -->
            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                {{ form.content }}
                {% if form.content.errors %}
                <div class="invalid-feedback">
                    {{ form.content.errors }}
                </div>
                {% endif %}
            </div>

            <!-- Tag Field -->
            <div class="mb-3">
                <label for="tags" class="form-label">Tags</label>
                <input type="text" class="form-control" id="tags" name="tags" value="{% if form.instance.pk %}{% with tags=form.instance.tags.all %}{% if tags %}{% for tag in tags %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}{% endwith %}{% endif %}">
            </div>

            <!-- Category Field -->
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <select id="category" name="category" class="form-select {% if form.category.errors %}is-invalid{% endif %}">
                    <option value="">-- 카테고리 선택 --</option>
                    {% for category in form.category.field.queryset %}
                    <option value="{{ category.id }}" {% if category.id == form.category.value %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
                {% if form.category.errors %}
                <div class="invalid-feedback">
                    {{ form.category.errors }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group text-center">
            <input type="submit" value="{% if form.instance.pk %}
                                          수정 완료
                                        {% else %}
                                          작성 완료
                                        {% endif %}" class="btn btn-primary btn-lg py-3 px-5">
        </div>
    </section>
</form>
{% endblock %}